version : '2'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "golang-apis"
    ports:
      - "5432:5432"
  
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: >
      sh -c "go run scripts/migrate.go && /golang-apis"

